<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Commentaire extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Commentaire_model');
    } 

    /*
     * Listing of commentaire
     */
    function index()
    {
        $data['commentaire'] = $this->Commentaire_model->get_all_commentaire();
        
        $data['_view'] = 'commentaire/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new commentaire
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('date_creation','Date Creation','required');
		$this->form_validation->set_rules('id_projet','Id Projet','integer');
		$this->form_validation->set_rules('id_createur','Id Createur','integer');
		$this->form_validation->set_rules('description','Description','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_projet' => $this->input->post('id_projet'),
				'id_createur' => $this->input->post('id_createur'),
				'date_creation' => $this->input->post('date_creation'),
				'description' => $this->input->post('description'),
            );
            
            $commentaire_id = $this->Commentaire_model->add_commentaire($params);
            redirect('commentaire/index');
        }
        else
        {
			$this->load->model('Projet_model');
			$data['all_projet'] = $this->Projet_model->get_all_projet();

			$this->load->model('Utilisateur_model');
			$data['all_utilisateur'] = $this->Utilisateur_model->get_all_utilisateur();
            
            $data['_view'] = 'commentaire/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a commentaire
     */
    function edit($id_commentaire)
    {   
        // check if the commentaire exists before trying to edit it
        $data['commentaire'] = $this->Commentaire_model->get_commentaire($id_commentaire);
        
        if(isset($data['commentaire']['id_commentaire']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('date_creation','Date Creation','required');
			$this->form_validation->set_rules('id_projet','Id Projet','integer');
			$this->form_validation->set_rules('id_createur','Id Createur','integer');
			$this->form_validation->set_rules('description','Description','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_projet' => $this->input->post('id_projet'),
					'id_createur' => $this->input->post('id_createur'),
					'date_creation' => $this->input->post('date_creation'),
					'description' => $this->input->post('description'),
                );

                $this->Commentaire_model->update_commentaire($id_commentaire,$params);            
                redirect('commentaire/index');
            }
            else
            {
				$this->load->model('Projet_model');
				$data['all_projet'] = $this->Projet_model->get_all_projet();

				$this->load->model('Utilisateur_model');
				$data['all_utilisateur'] = $this->Utilisateur_model->get_all_utilisateur();

                $data['_view'] = 'commentaire/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The commentaire you are trying to edit does not exist.');
    } 

    /*
     * Deleting commentaire
     */
    function remove($id_commentaire)
    {
        $commentaire = $this->Commentaire_model->get_commentaire($id_commentaire);

        // check if the commentaire exists before trying to delete it
        if(isset($commentaire['id_commentaire']))
        {
            $this->Commentaire_model->delete_commentaire($id_commentaire);
            redirect('commentaire/index');
        }
        else
            show_error('The commentaire you are trying to delete does not exist.');
    }
    
}
