<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Equipe extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Equipe_model');
    } 

    /*
     * Listing of equipe
     */
    function index()
    {
        $data['equipe'] = $this->Equipe_model->get_all_equipe();
        
        $data['_view'] = 'equipe/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new equipe
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nom','Nom','required|max_length[50]');
		$this->form_validation->set_rules('titre_emploi','Titre Emploi','required|max_length[100]');
		$this->form_validation->set_rules('id_createur','Id Createur','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_createur' => $this->input->post('id_createur'),
				'nom' => $this->input->post('nom'),
				'titre_emploi' => $this->input->post('titre_emploi'),
            );
            
            $equipe_id = $this->Equipe_model->add_equipe($params);
            redirect('equipe/index');
        }
        else
        {
			$this->load->model('Utilisateur_model');
			$data['all_utilisateur'] = $this->Utilisateur_model->get_all_utilisateur();
            
            $data['_view'] = 'equipe/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a equipe
     */
    function edit($id_equipe)
    {   
        // check if the equipe exists before trying to edit it
        $data['equipe'] = $this->Equipe_model->get_equipe($id_equipe);
        
        if(isset($data['equipe']['id_equipe']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nom','Nom','required|max_length[50]');
			$this->form_validation->set_rules('titre_emploi','Titre Emploi','required|max_length[100]');
			$this->form_validation->set_rules('id_createur','Id Createur','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_createur' => $this->input->post('id_createur'),
					'nom' => $this->input->post('nom'),
					'titre_emploi' => $this->input->post('titre_emploi'),
                );

                $this->Equipe_model->update_equipe($id_equipe,$params);            
                redirect('equipe/index');
            }
            else
            {
				$this->load->model('Utilisateur_model');
				$data['all_utilisateur'] = $this->Utilisateur_model->get_all_utilisateur();

                $data['_view'] = 'equipe/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The equipe you are trying to edit does not exist.');
    } 

    /*
     * Deleting equipe
     */
    function remove($id_equipe)
    {
        $equipe = $this->Equipe_model->get_equipe($id_equipe);

        // check if the equipe exists before trying to delete it
        if(isset($equipe['id_equipe']))
        {
            $this->Equipe_model->delete_equipe($id_equipe);
            redirect('equipe/index');
        }
        else
            show_error('The equipe you are trying to delete does not exist.');
    }
    
}
