<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Equipe_a_projet extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Equipe_a_projet_model');
    } 

    /*
     * Listing of equipe_a_projet
     */
    function index()
    {
        $data['equipe_a_projet'] = $this->Equipe_a_projet_model->get_all_equipe_a_projet();
        
        $data['_view'] = 'equipe_a_projet/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new equipe_a_projet
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_projet' => $this->input->post('id_projet'),
				'id_equipe' => $this->input->post('id_equipe'),
            );
            
            $equipe_a_projet_id = $this->Equipe_a_projet_model->add_equipe_a_projet($params);
            redirect('equipe_a_projet/index');
        }
        else
        {
			$this->load->model('Projet_model');
			$data['all_projet'] = $this->Projet_model->get_all_projet();

			$this->load->model('Equipe_model');
			$data['all_equipe'] = $this->Equipe_model->get_all_equipe();
            
            $data['_view'] = 'equipe_a_projet/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a equipe_a_projet
     */
    function edit($)
    {   
        // check if the equipe_a_projet exists before trying to edit it
        $data['equipe_a_projet'] = $this->Equipe_a_projet_model->get_equipe_a_projet($);
        
        if(isset($data['equipe_a_projet']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_projet' => $this->input->post('id_projet'),
					'id_equipe' => $this->input->post('id_equipe'),
                );

                $this->Equipe_a_projet_model->update_equipe_a_projet($,$params);            
                redirect('equipe_a_projet/index');
            }
            else
            {
				$this->load->model('Projet_model');
				$data['all_projet'] = $this->Projet_model->get_all_projet();

				$this->load->model('Equipe_model');
				$data['all_equipe'] = $this->Equipe_model->get_all_equipe();

                $data['_view'] = 'equipe_a_projet/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The equipe_a_projet you are trying to edit does not exist.');
    } 

    /*
     * Deleting equipe_a_projet
     */
    function remove($)
    {
        $equipe_a_projet = $this->Equipe_a_projet_model->get_equipe_a_projet($);

        // check if the equipe_a_projet exists before trying to delete it
        if(isset($equipe_a_projet['']))
        {
            $this->Equipe_a_projet_model->delete_equipe_a_projet($);
            redirect('equipe_a_projet/index');
        }
        else
            show_error('The equipe_a_projet you are trying to delete does not exist.');
    }
    
}
