<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fichier extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fichier_model');
    } 

    /*
     * Listing of fichier
     */
    function index()
    {
        $data['fichier'] = $this->Fichier_model->get_all_fichier();
        
        $data['_view'] = 'fichier/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new fichier
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nom','Nom','required|max_length[150]');
		$this->form_validation->set_rules('size','Size','required');
		$this->form_validation->set_rules('date_creation','Date Creation','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_projet' => $this->input->post('id_projet'),
				'telecharge_par' => $this->input->post('telecharge_par'),
				'nom' => $this->input->post('nom'),
				'size' => $this->input->post('size'),
				'date_creation' => $this->input->post('date_creation'),
				'description' => $this->input->post('description'),
            );
            
            $fichier_id = $this->Fichier_model->add_fichier($params);
            redirect('fichier/index');
        }
        else
        {
			$this->load->model('Projet_model');
			$data['all_projet'] = $this->Projet_model->get_all_projet();

			$this->load->model('Utilisateur_model');
			$data['all_utilisateur'] = $this->Utilisateur_model->get_all_utilisateur();
            
            $data['_view'] = 'fichier/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a fichier
     */
    function edit($id_fichier)
    {   
        // check if the fichier exists before trying to edit it
        $data['fichier'] = $this->Fichier_model->get_fichier($id_fichier);
        
        if(isset($data['fichier']['id_fichier']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nom','Nom','required|max_length[150]');
			$this->form_validation->set_rules('size','Size','required');
			$this->form_validation->set_rules('date_creation','Date Creation','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_projet' => $this->input->post('id_projet'),
					'telecharge_par' => $this->input->post('telecharge_par'),
					'nom' => $this->input->post('nom'),
					'size' => $this->input->post('size'),
					'date_creation' => $this->input->post('date_creation'),
					'description' => $this->input->post('description'),
                );

                $this->Fichier_model->update_fichier($id_fichier,$params);            
                redirect('fichier/index');
            }
            else
            {
				$this->load->model('Projet_model');
				$data['all_projet'] = $this->Projet_model->get_all_projet();

				$this->load->model('Utilisateur_model');
				$data['all_utilisateur'] = $this->Utilisateur_model->get_all_utilisateur();

                $data['_view'] = 'fichier/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The fichier you are trying to edit does not exist.');
    } 

    /*
     * Deleting fichier
     */
    function remove($id_fichier)
    {
        $fichier = $this->Fichier_model->get_fichier($id_fichier);

        // check if the fichier exists before trying to delete it
        if(isset($fichier['id_fichier']))
        {
            $this->Fichier_model->delete_fichier($id_fichier);
            redirect('fichier/index');
        }
        else
            show_error('The fichier you are trying to delete does not exist.');
    }
    
}
