<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Projet extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Projet_model');
    } 

    /*
     * Listing of projet
     */
    function index()
    {
        $data['projet'] = $this->Projet_model->get_all_projet();
        
        $data['_view'] = 'projet/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new projet
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('titre','Titre','required|max_length[50]');
		$this->form_validation->set_rules('date_debut','Date Debut','required');
		$this->form_validation->set_rules('date_limite','Date Limite','required');
		$this->form_validation->set_rules('date_creation','Date Creation','required');
		$this->form_validation->set_rules('status','Status','required');
		$this->form_validation->set_rules('description','Description','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_client' => $this->input->post('id_client'),
				'titre' => $this->input->post('titre'),
				'date_debut' => $this->input->post('date_debut'),
				'date_limite' => $this->input->post('date_limite'),
				'date_creation' => $this->input->post('date_creation'),
				'status' => $this->input->post('status'),
				'prix' => $this->input->post('prix'),
				'description' => $this->input->post('description'),
            );
            
            $projet_id = $this->Projet_model->add_projet($params);
            redirect('projet/index');
        }
        else
        {
			$this->load->model('Client_model');
			$data['all_client'] = $this->Client_model->get_all_client();
            
            $data['_view'] = 'projet/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a projet
     */
    function edit($id_projet)
    {   
        // check if the projet exists before trying to edit it
        $data['projet'] = $this->Projet_model->get_projet($id_projet);
        
        if(isset($data['projet']['id_projet']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('titre','Titre','required|max_length[50]');
			$this->form_validation->set_rules('date_debut','Date Debut','required');
			$this->form_validation->set_rules('date_limite','Date Limite','required');
			$this->form_validation->set_rules('date_creation','Date Creation','required');
			$this->form_validation->set_rules('status','Status','required');
			$this->form_validation->set_rules('description','Description','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_client' => $this->input->post('id_client'),
					'titre' => $this->input->post('titre'),
					'date_debut' => $this->input->post('date_debut'),
					'date_limite' => $this->input->post('date_limite'),
					'date_creation' => $this->input->post('date_creation'),
					'status' => $this->input->post('status'),
					'prix' => $this->input->post('prix'),
					'description' => $this->input->post('description'),
                );

                $this->Projet_model->update_projet($id_projet,$params);            
                redirect('projet/index');
            }
            else
            {
				$this->load->model('Client_model');
				$data['all_client'] = $this->Client_model->get_all_client();

                $data['_view'] = 'projet/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The projet you are trying to edit does not exist.');
    } 

    /*
     * Deleting projet
     */
    function remove($id_projet)
    {
        $projet = $this->Projet_model->get_projet($id_projet);

        // check if the projet exists before trying to delete it
        if(isset($projet['id_projet']))
        {
            $this->Projet_model->delete_projet($id_projet);
            redirect('projet/index');
        }
        else
            show_error('The projet you are trying to delete does not exist.');
    }
    
}
