<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tache extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tache_model');
    } 

    /*
     * Listing of tache
     */
    function index()
    {
        $data['tache'] = $this->Tache_model->get_all_tache();
        
        $data['_view'] = 'tache/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tache
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('titre','Titre','required|max_length[50]');
		$this->form_validation->set_rules('date_debut','Date Debut','required');
		$this->form_validation->set_rules('date_limite','Date Limite','required');
		$this->form_validation->set_rules('status','Status','required');
		$this->form_validation->set_rules('description','Description','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_projet' => $this->input->post('id_projet'),
				'assigne_a' => $this->input->post('assigne_a'),
				'titre' => $this->input->post('titre'),
				'date_debut' => $this->input->post('date_debut'),
				'date_limite' => $this->input->post('date_limite'),
				'status' => $this->input->post('status'),
				'description' => $this->input->post('description'),
            );
            
            $tache_id = $this->Tache_model->add_tache($params);
            redirect('tache/index');
        }
        else
        {
			$this->load->model('Projet_model');
			$data['all_projet'] = $this->Projet_model->get_all_projet();

			$this->load->model('Utilisateur_model');
			$data['all_utilisateur'] = $this->Utilisateur_model->get_all_utilisateur();
            
            $data['_view'] = 'tache/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tache
     */
    function edit($id_tache)
    {   
        // check if the tache exists before trying to edit it
        $data['tache'] = $this->Tache_model->get_tache($id_tache);
        
        if(isset($data['tache']['id_tache']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('titre','Titre','required|max_length[50]');
			$this->form_validation->set_rules('date_debut','Date Debut','required');
			$this->form_validation->set_rules('date_limite','Date Limite','required');
			$this->form_validation->set_rules('status','Status','required');
			$this->form_validation->set_rules('description','Description','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_projet' => $this->input->post('id_projet'),
					'assigne_a' => $this->input->post('assigne_a'),
					'titre' => $this->input->post('titre'),
					'date_debut' => $this->input->post('date_debut'),
					'date_limite' => $this->input->post('date_limite'),
					'status' => $this->input->post('status'),
					'description' => $this->input->post('description'),
                );

                $this->Tache_model->update_tache($id_tache,$params);            
                redirect('tache/index');
            }
            else
            {
				$this->load->model('Projet_model');
				$data['all_projet'] = $this->Projet_model->get_all_projet();

				$this->load->model('Utilisateur_model');
				$data['all_utilisateur'] = $this->Utilisateur_model->get_all_utilisateur();

                $data['_view'] = 'tache/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tache you are trying to edit does not exist.');
    } 

    /*
     * Deleting tache
     */
    function remove($id_tache)
    {
        $tache = $this->Tache_model->get_tache($id_tache);

        // check if the tache exists before trying to delete it
        if(isset($tache['id_tache']))
        {
            $this->Tache_model->delete_tache($id_tache);
            redirect('tache/index');
        }
        else
            show_error('The tache you are trying to delete does not exist.');
    }
    
}
