<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Utilisateur_a_equipe extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Utilisateur_a_equipe_model');
    } 

    /*
     * Listing of utilisateur_a_equipe
     */
    function index()
    {
        $data['utilisateur_a_equipe'] = $this->Utilisateur_a_equipe_model->get_all_utilisateur_a_equipe();
        
        $data['_view'] = 'utilisateur_a_equipe/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new utilisateur_a_equipe
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_utilisateur' => $this->input->post('id_utilisateur'),
				'id_equipe' => $this->input->post('id_equipe'),
            );
            
            $utilisateur_a_equipe_id = $this->Utilisateur_a_equipe_model->add_utilisateur_a_equipe($params);
            redirect('utilisateur_a_equipe/index');
        }
        else
        {
			$this->load->model('Utilisateur_model');
			$data['all_utilisateur'] = $this->Utilisateur_model->get_all_utilisateur();

			$this->load->model('Equipe_model');
			$data['all_equipe'] = $this->Equipe_model->get_all_equipe();
            
            $data['_view'] = 'utilisateur_a_equipe/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a utilisateur_a_equipe
     */
    function edit($)
    {   
        // check if the utilisateur_a_equipe exists before trying to edit it
        $data['utilisateur_a_equipe'] = $this->Utilisateur_a_equipe_model->get_utilisateur_a_equipe($);
        
        if(isset($data['utilisateur_a_equipe']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_utilisateur' => $this->input->post('id_utilisateur'),
					'id_equipe' => $this->input->post('id_equipe'),
                );

                $this->Utilisateur_a_equipe_model->update_utilisateur_a_equipe($,$params);            
                redirect('utilisateur_a_equipe/index');
            }
            else
            {
				$this->load->model('Utilisateur_model');
				$data['all_utilisateur'] = $this->Utilisateur_model->get_all_utilisateur();

				$this->load->model('Equipe_model');
				$data['all_equipe'] = $this->Equipe_model->get_all_equipe();

                $data['_view'] = 'utilisateur_a_equipe/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The utilisateur_a_equipe you are trying to edit does not exist.');
    } 

    /*
     * Deleting utilisateur_a_equipe
     */
    function remove($)
    {
        $utilisateur_a_equipe = $this->Utilisateur_a_equipe_model->get_utilisateur_a_equipe($);

        // check if the utilisateur_a_equipe exists before trying to delete it
        if(isset($utilisateur_a_equipe['']))
        {
            $this->Utilisateur_a_equipe_model->delete_utilisateur_a_equipe($);
            redirect('utilisateur_a_equipe/index');
        }
        else
            show_error('The utilisateur_a_equipe you are trying to delete does not exist.');
    }
    
}
