<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Commentaire_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get commentaire by id_commentaire
     */
    function get_commentaire($id_commentaire)
    {
        return $this->db->get_where('commentaire',array('id_commentaire'=>$id_commentaire))->row_array();
    }
        
    /*
     * Get all commentaire
     */
    function get_all_commentaire()
    {
        $this->db->order_by('id_commentaire', 'desc');
        return $this->db->get('commentaire')->result_array();
    }
        
    /*
     * function to add new commentaire
     */
    function add_commentaire($params)
    {
        $this->db->insert('commentaire',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update commentaire
     */
    function update_commentaire($id_commentaire,$params)
    {
        $this->db->where('id_commentaire',$id_commentaire);
        return $this->db->update('commentaire',$params);
    }
    
    /*
     * function to delete commentaire
     */
    function delete_commentaire($id_commentaire)
    {
        return $this->db->delete('commentaire',array('id_commentaire'=>$id_commentaire));
    }
}
