<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Equipe_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get equipe by id_equipe
     */
    function get_equipe($id_equipe)
    {
        return $this->db->get_where('equipe',array('id_equipe'=>$id_equipe))->row_array();
    }
        
    /*
     * Get all equipe
     */
    function get_all_equipe()
    {
        $this->db->order_by('id_equipe', 'desc');
        return $this->db->get('equipe')->result_array();
    }
        
    /*
     * function to add new equipe
     */
    function add_equipe($params)
    {
        $this->db->insert('equipe',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update equipe
     */
    function update_equipe($id_equipe,$params)
    {
        $this->db->where('id_equipe',$id_equipe);
        return $this->db->update('equipe',$params);
    }
    
    /*
     * function to delete equipe
     */
    function delete_equipe($id_equipe)
    {
        return $this->db->delete('equipe',array('id_equipe'=>$id_equipe));
    }
}
