<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Equipe_a_projet_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get equipe_a_projet by 
     */
    function get_equipe_a_projet($)
    {
        return $this->db->get_where('equipe_a_projet',array(''=>$))->row_array();
    }
        
    /*
     * Get all equipe_a_projet
     */
    function get_all_equipe_a_projet()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('equipe_a_projet')->result_array();
    }
        
    /*
     * function to add new equipe_a_projet
     */
    function add_equipe_a_projet($params)
    {
        $this->db->insert('equipe_a_projet',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update equipe_a_projet
     */
    function update_equipe_a_projet($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('equipe_a_projet',$params);
    }
    
    /*
     * function to delete equipe_a_projet
     */
    function delete_equipe_a_projet($)
    {
        return $this->db->delete('equipe_a_projet',array(''=>$));
    }
}
