<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Facture_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get facture by id_facture
     */
    function get_facture($id_facture)
    {
        return $this->db->get_where('facture',array('id_facture'=>$id_facture))->row_array();
    }
        
    /*
     * Get all facture
     */
    function get_all_facture()
    {
        $this->db->order_by('id_facture', 'desc');
        return $this->db->get('facture')->result_array();
    }
        
    /*
     * function to add new facture
     */
    function add_facture($params)
    {
        $this->db->insert('facture',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update facture
     */
    function update_facture($id_facture,$params)
    {
        $this->db->where('id_facture',$id_facture);
        return $this->db->update('facture',$params);
    }
    
    /*
     * function to delete facture
     */
    function delete_facture($id_facture)
    {
        return $this->db->delete('facture',array('id_facture'=>$id_facture));
    }
}
