<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fichier_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fichier by id_fichier
     */
    function get_fichier($id_fichier)
    {
        return $this->db->get_where('fichier',array('id_fichier'=>$id_fichier))->row_array();
    }
        
    /*
     * Get all fichier
     */
    function get_all_fichier()
    {
        $this->db->order_by('id_fichier', 'desc');
        return $this->db->get('fichier')->result_array();
    }
        
    /*
     * function to add new fichier
     */
    function add_fichier($params)
    {
        $this->db->insert('fichier',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fichier
     */
    function update_fichier($id_fichier,$params)
    {
        $this->db->where('id_fichier',$id_fichier);
        return $this->db->update('fichier',$params);
    }
    
    /*
     * function to delete fichier
     */
    function delete_fichier($id_fichier)
    {
        return $this->db->delete('fichier',array('id_fichier'=>$id_fichier));
    }
}
