<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Note_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get note by id_note
     */
    function get_note($id_note)
    {
        return $this->db->get_where('note',array('id_note'=>$id_note))->row_array();
    }
        
    /*
     * Get all note
     */
    function get_all_note()
    {
        $this->db->order_by('id_note', 'desc');
        return $this->db->get('note')->result_array();
    }
        
    /*
     * function to add new note
     */
    function add_note($params)
    {
        $this->db->insert('note',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update note
     */
    function update_note($id_note,$params)
    {
        $this->db->where('id_note',$id_note);
        return $this->db->update('note',$params);
    }
    
    /*
     * function to delete note
     */
    function delete_note($id_note)
    {
        return $this->db->delete('note',array('id_note'=>$id_note));
    }
}
