<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Projet_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get projet by id_projet
     */
    function get_projet($id_projet)
    {
        return $this->db->get_where('projet',array('id_projet'=>$id_projet))->row_array();
    }
        
    /*
     * Get all projet
     */
    function get_all_projet()
    {
        $this->db->order_by('id_projet', 'desc');
        return $this->db->get('projet')->result_array();
    }
        
    /*
     * function to add new projet
     */
    function add_projet($params)
    {
        $this->db->insert('projet',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update projet
     */
    function update_projet($id_projet,$params)
    {
        $this->db->where('id_projet',$id_projet);
        return $this->db->update('projet',$params);
    }
    
    /*
     * function to delete projet
     */
    function delete_projet($id_projet)
    {
        return $this->db->delete('projet',array('id_projet'=>$id_projet));
    }
}
