<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tache_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tache by id_tache
     */
    function get_tache($id_tache)
    {
        return $this->db->get_where('tache',array('id_tache'=>$id_tache))->row_array();
    }
        
    /*
     * Get all tache
     */
    function get_all_tache()
    {
        $this->db->order_by('id_tache', 'desc');
        return $this->db->get('tache')->result_array();
    }
        
    /*
     * function to add new tache
     */
    function add_tache($params)
    {
        $this->db->insert('tache',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tache
     */
    function update_tache($id_tache,$params)
    {
        $this->db->where('id_tache',$id_tache);
        return $this->db->update('tache',$params);
    }
    
    /*
     * function to delete tache
     */
    function delete_tache($id_tache)
    {
        return $this->db->delete('tache',array('id_tache'=>$id_tache));
    }
}
