<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Utilisateur_a_equipe_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get utilisateur_a_equipe by 
     */
    function get_utilisateur_a_equipe($)
    {
        return $this->db->get_where('utilisateur_a_equipe',array(''=>$))->row_array();
    }
        
    /*
     * Get all utilisateur_a_equipe
     */
    function get_all_utilisateur_a_equipe()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('utilisateur_a_equipe')->result_array();
    }
        
    /*
     * function to add new utilisateur_a_equipe
     */
    function add_utilisateur_a_equipe($params)
    {
        $this->db->insert('utilisateur_a_equipe',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update utilisateur_a_equipe
     */
    function update_utilisateur_a_equipe($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('utilisateur_a_equipe',$params);
    }
    
    /*
     * function to delete utilisateur_a_equipe
     */
    function delete_utilisateur_a_equipe($)
    {
        return $this->db->delete('utilisateur_a_equipe',array(''=>$));
    }
}
