<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Utilisateur_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get utilisateur by id_utilisateur
     */
    function get_utilisateur($id_utilisateur)
    {
        return $this->db->get_where('utilisateur',array('id_utilisateur'=>$id_utilisateur))->row_array();
    }
        
    /*
     * Get all utilisateur
     */
    function get_all_utilisateur()
    {
        $this->db->order_by('id_utilisateur', 'desc');
        return $this->db->get('utilisateur')->result_array();
    }
        
    /*
     * function to add new utilisateur
     */
    function add_utilisateur($params)
    {
        $this->db->insert('utilisateur',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update utilisateur
     */
    function update_utilisateur($id_utilisateur,$params)
    {
        $this->db->where('id_utilisateur',$id_utilisateur);
        return $this->db->update('utilisateur',$params);
    }
    
    /*
     * function to delete utilisateur
     */
    function delete_utilisateur($id_utilisateur)
    {
        return $this->db->delete('utilisateur',array('id_utilisateur'=>$id_utilisateur));
    }
}
